### ISSUE TITLE
p138 代码报错

### ISSUE THREAD

**Issue by shaodamao** [qiyeboy/SpiderBook#6]
Traceback (most recent call last):
  File "C:/spider/chapter5_4.py", line 25, in <module>
    server = smtplib.SMTP(smtp_server, 25)
  File "C:\Python27\Lib\smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "C:\Python27\Lib\smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "C:\Python27\Lib\smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "C:\Python27\Lib\socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno 11001] getaddrinfo failed

这个是什么问题呢

**Comment by qiyeboy** [comment]
是代码中smtp_server = 'smtp.163.com'，最后没有空格，已修正
