### ISSUE TITLE
第六章

### ISSUE THREAD

**Issue by Stone-Stone** [qiyeboy/SpiderBook#98]
出现如下错误：
Traceback (most recent call last):
  File "E:/PythonProjects/py_spider/spider_1.py/SpiderMan.py", line 43, in <module>
    spider_man.crawl(root_url)
  File "E:/PythonProjects/py_spider/spider_1.py/SpiderMan.py", line 20, in crawl
    self.manager.add_new_url(root_url)
TypeError: add_new_url() missing 1 required positional argument: 'url'

**Comment by Stone-Stone** [comment]
已解决，对象初始化的问题。
